// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: predictor.proto

package predictorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutputTokenPredictor_Health_FullMethodName       = "/predictor.v1.OutputTokenPredictor/Health"
	OutputTokenPredictor_BatchPredict_FullMethodName = "/predictor.v1.OutputTokenPredictor/BatchPredict"
)

// OutputTokenPredictorClient is the client API for OutputTokenPredictor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutputTokenPredictorClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	BatchPredict(ctx context.Context, in *BatchPredictRequest, opts ...grpc.CallOption) (*BatchPredictResponse, error)
}

type outputTokenPredictorClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputTokenPredictorClient(cc grpc.ClientConnInterface) OutputTokenPredictorClient {
	return &outputTokenPredictorClient{cc}
}

func (c *outputTokenPredictorClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, OutputTokenPredictor_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputTokenPredictorClient) BatchPredict(ctx context.Context, in *BatchPredictRequest, opts ...grpc.CallOption) (*BatchPredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPredictResponse)
	err := c.cc.Invoke(ctx, OutputTokenPredictor_BatchPredict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputTokenPredictorServer is the server API for OutputTokenPredictor service.
// All implementations must embed UnimplementedOutputTokenPredictorServer
// for forward compatibility.
type OutputTokenPredictorServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	BatchPredict(context.Context, *BatchPredictRequest) (*BatchPredictResponse, error)
	mustEmbedUnimplementedOutputTokenPredictorServer()
}

// UnimplementedOutputTokenPredictorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutputTokenPredictorServer struct{}

func (UnimplementedOutputTokenPredictorServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedOutputTokenPredictorServer) BatchPredict(context.Context, *BatchPredictRequest) (*BatchPredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPredict not implemented")
}
func (UnimplementedOutputTokenPredictorServer) mustEmbedUnimplementedOutputTokenPredictorServer() {}
func (UnimplementedOutputTokenPredictorServer) testEmbeddedByValue()                              {}

// UnsafeOutputTokenPredictorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputTokenPredictorServer will
// result in compilation errors.
type UnsafeOutputTokenPredictorServer interface {
	mustEmbedUnimplementedOutputTokenPredictorServer()
}

func RegisterOutputTokenPredictorServer(s grpc.ServiceRegistrar, srv OutputTokenPredictorServer) {
	// If the following call pancis, it indicates UnimplementedOutputTokenPredictorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutputTokenPredictor_ServiceDesc, srv)
}

func _OutputTokenPredictor_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputTokenPredictorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputTokenPredictor_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputTokenPredictorServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputTokenPredictor_BatchPredict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputTokenPredictorServer).BatchPredict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputTokenPredictor_BatchPredict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputTokenPredictorServer).BatchPredict(ctx, req.(*BatchPredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutputTokenPredictor_ServiceDesc is the grpc.ServiceDesc for OutputTokenPredictor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputTokenPredictor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "predictor.v1.OutputTokenPredictor",
	HandlerType: (*OutputTokenPredictorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _OutputTokenPredictor_Health_Handler,
		},
		{
			MethodName: "BatchPredict",
			Handler:    _OutputTokenPredictor_BatchPredict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "predictor.proto",
}
