// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: predictor.proto

package predictorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_predictor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_predictor_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_predictor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_predictor_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BatchPredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskFeature         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictRequest) Reset() {
	*x = BatchPredictRequest{}
	mi := &file_predictor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictRequest) ProtoMessage() {}

func (x *BatchPredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictRequest.ProtoReflect.Descriptor instead.
func (*BatchPredictRequest) Descriptor() ([]byte, []int) {
	return file_predictor_proto_rawDescGZIP(), []int{2}
}

func (x *BatchPredictRequest) GetTasks() []*TaskFeature {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskFeature struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TaskId                   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ModelClass               string                 `protobuf:"bytes,2,opt,name=model_class,json=modelClass,proto3" json:"model_class,omitempty"`
	EstimatedInputTokens     int64                  `protobuf:"varint,3,opt,name=estimated_input_tokens,json=estimatedInputTokens,proto3" json:"estimated_input_tokens,omitempty"`
	EstimatedOutputTokens    int64                  `protobuf:"varint,4,opt,name=estimated_output_tokens,json=estimatedOutputTokens,proto3" json:"estimated_output_tokens,omitempty"`
	Stream                   bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	Priority                 string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutClass             string                 `protobuf:"bytes,7,opt,name=timeout_class,json=timeoutClass,proto3" json:"timeout_class,omitempty"`
	EnqueueTimeMs            int64                  `protobuf:"varint,8,opt,name=enqueue_time_ms,json=enqueueTimeMs,proto3" json:"enqueue_time_ms,omitempty"`
	RequestKind              string                 `protobuf:"bytes,9,opt,name=request_kind,json=requestKind,proto3" json:"request_kind,omitempty"`
	RouteHint                string                 `protobuf:"bytes,10,opt,name=route_hint,json=routeHint,proto3" json:"route_hint,omitempty"`
	HasToolCalls             bool                   `protobuf:"varint,11,opt,name=has_tool_calls,json=hasToolCalls,proto3" json:"has_tool_calls,omitempty"`
	ToolCallDepth            int32                  `protobuf:"varint,12,opt,name=tool_call_depth,json=toolCallDepth,proto3" json:"tool_call_depth,omitempty"`
	TurnCount                int32                  `protobuf:"varint,13,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	Multimodal               bool                   `protobuf:"varint,14,opt,name=multimodal,proto3" json:"multimodal,omitempty"`
	QuestionCount            int32                  `protobuf:"varint,15,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	CodeBlockCount           int32                  `protobuf:"varint,16,opt,name=code_block_count,json=codeBlockCount,proto3" json:"code_block_count,omitempty"`
	EnumerationHint          bool                   `protobuf:"varint,17,opt,name=enumeration_hint,json=enumerationHint,proto3" json:"enumeration_hint,omitempty"`
	InstructionVerbCount     int32                  `protobuf:"varint,18,opt,name=instruction_verb_count,json=instructionVerbCount,proto3" json:"instruction_verb_count,omitempty"`
	MaxSentenceLengthBucket  int32                  `protobuf:"varint,19,opt,name=max_sentence_length_bucket,json=maxSentenceLengthBucket,proto3" json:"max_sentence_length_bucket,omitempty"`
	VocabularyRichnessBucket int32                  `protobuf:"varint,20,opt,name=vocabulary_richness_bucket,json=vocabularyRichnessBucket,proto3" json:"vocabulary_richness_bucket,omitempty"`
	ConfidenceHint           float64                `protobuf:"fixed64,21,opt,name=confidence_hint,json=confidenceHint,proto3" json:"confidence_hint,omitempty"`
	UncertaintyHint          float64                `protobuf:"fixed64,22,opt,name=uncertainty_hint,json=uncertaintyHint,proto3" json:"uncertainty_hint,omitempty"`
	NeighborCount            int64                  `protobuf:"varint,23,opt,name=neighbor_count,json=neighborCount,proto3" json:"neighbor_count,omitempty"`
	LatencyP50Ms             int64                  `protobuf:"varint,24,opt,name=latency_p50_ms,json=latencyP50Ms,proto3" json:"latency_p50_ms,omitempty"`
	LatencyP90Ms             int64                  `protobuf:"varint,25,opt,name=latency_p90_ms,json=latencyP90Ms,proto3" json:"latency_p90_ms,omitempty"`
	LatencyStddevMs          float64                `protobuf:"fixed64,26,opt,name=latency_stddev_ms,json=latencyStddevMs,proto3" json:"latency_stddev_ms,omitempty"`
	OutputTokensP70          int64                  `protobuf:"varint,27,opt,name=output_tokens_p70,json=outputTokensP70,proto3" json:"output_tokens_p70,omitempty"`
	SuccessRate              float64                `protobuf:"fixed64,28,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	TimeoutRate              float64                `protobuf:"fixed64,29,opt,name=timeout_rate,json=timeoutRate,proto3" json:"timeout_rate,omitempty"`
	CoverageLevel            string                 `protobuf:"bytes,30,opt,name=coverage_level,json=coverageLevel,proto3" json:"coverage_level,omitempty"`
	CoverageRatio            float64                `protobuf:"fixed64,31,opt,name=coverage_ratio,json=coverageRatio,proto3" json:"coverage_ratio,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TaskFeature) Reset() {
	*x = TaskFeature{}
	mi := &file_predictor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFeature) ProtoMessage() {}

func (x *TaskFeature) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFeature.ProtoReflect.Descriptor instead.
func (*TaskFeature) Descriptor() ([]byte, []int) {
	return file_predictor_proto_rawDescGZIP(), []int{3}
}

func (x *TaskFeature) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFeature) GetModelClass() string {
	if x != nil {
		return x.ModelClass
	}
	return ""
}

func (x *TaskFeature) GetEstimatedInputTokens() int64 {
	if x != nil {
		return x.EstimatedInputTokens
	}
	return 0
}

func (x *TaskFeature) GetEstimatedOutputTokens() int64 {
	if x != nil {
		return x.EstimatedOutputTokens
	}
	return 0
}

func (x *TaskFeature) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *TaskFeature) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *TaskFeature) GetTimeoutClass() string {
	if x != nil {
		return x.TimeoutClass
	}
	return ""
}

func (x *TaskFeature) GetEnqueueTimeMs() int64 {
	if x != nil {
		return x.EnqueueTimeMs
	}
	return 0
}

func (x *TaskFeature) GetRequestKind() string {
	if x != nil {
		return x.RequestKind
	}
	return ""
}

func (x *TaskFeature) GetRouteHint() string {
	if x != nil {
		return x.RouteHint
	}
	return ""
}

func (x *TaskFeature) GetHasToolCalls() bool {
	if x != nil {
		return x.HasToolCalls
	}
	return false
}

func (x *TaskFeature) GetToolCallDepth() int32 {
	if x != nil {
		return x.ToolCallDepth
	}
	return 0
}

func (x *TaskFeature) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *TaskFeature) GetMultimodal() bool {
	if x != nil {
		return x.Multimodal
	}
	return false
}

func (x *TaskFeature) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *TaskFeature) GetCodeBlockCount() int32 {
	if x != nil {
		return x.CodeBlockCount
	}
	return 0
}

func (x *TaskFeature) GetEnumerationHint() bool {
	if x != nil {
		return x.EnumerationHint
	}
	return false
}

func (x *TaskFeature) GetInstructionVerbCount() int32 {
	if x != nil {
		return x.InstructionVerbCount
	}
	return 0
}

func (x *TaskFeature) GetMaxSentenceLengthBucket() int32 {
	if x != nil {
		return x.MaxSentenceLengthBucket
	}
	return 0
}

func (x *TaskFeature) GetVocabularyRichnessBucket() int32 {
	if x != nil {
		return x.VocabularyRichnessBucket
	}
	return 0
}

func (x *TaskFeature) GetConfidenceHint() float64 {
	if x != nil {
		return x.ConfidenceHint
	}
	return 0
}

func (x *TaskFeature) GetUncertaintyHint() float64 {
	if x != nil {
		return x.UncertaintyHint
	}
	return 0
}

func (x *TaskFeature) GetNeighborCount() int64 {
	if x != nil {
		return x.NeighborCount
	}
	return 0
}

func (x *TaskFeature) GetLatencyP50Ms() int64 {
	if x != nil {
		return x.LatencyP50Ms
	}
	return 0
}

func (x *TaskFeature) GetLatencyP90Ms() int64 {
	if x != nil {
		return x.LatencyP90Ms
	}
	return 0
}

func (x *TaskFeature) GetLatencyStddevMs() float64 {
	if x != nil {
		return x.LatencyStddevMs
	}
	return 0
}

func (x *TaskFeature) GetOutputTokensP70() int64 {
	if x != nil {
		return x.OutputTokensP70
	}
	return 0
}

func (x *TaskFeature) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *TaskFeature) GetTimeoutRate() float64 {
	if x != nil {
		return x.TimeoutRate
	}
	return 0
}

func (x *TaskFeature) GetCoverageLevel() string {
	if x != nil {
		return x.CoverageLevel
	}
	return ""
}

func (x *TaskFeature) GetCoverageRatio() float64 {
	if x != nil {
		return x.CoverageRatio
	}
	return 0
}

type BatchPredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []*Prediction          `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictResponse) Reset() {
	*x = BatchPredictResponse{}
	mi := &file_predictor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictResponse) ProtoMessage() {}

func (x *BatchPredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictResponse.ProtoReflect.Descriptor instead.
func (*BatchPredictResponse) Descriptor() ([]byte, []int) {
	return file_predictor_proto_rawDescGZIP(), []int{4}
}

func (x *BatchPredictResponse) GetPredictions() []*Prediction {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type Prediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantiles     map[int32]float64      `protobuf:"bytes,1,rep,name=quantiles,proto3" json:"quantiles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Signals       map[string]float64     `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_predictor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_predictor_proto_rawDescGZIP(), []int{5}
}

func (x *Prediction) GetQuantiles() map[int32]float64 {
	if x != nil {
		return x.Quantiles
	}
	return nil
}

func (x *Prediction) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *Prediction) GetSignals() map[string]float64 {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *Prediction) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_predictor_proto protoreflect.FileDescriptor

const file_predictor_proto_rawDesc = "" +
	"\n" +
	"\x0fpredictor.proto\x12\fpredictor.v1\"\x0f\n" +
	"\rHealthRequest\"c\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"F\n" +
	"\x13BatchPredictRequest\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.predictor.v1.TaskFeatureR\x05tasks\"\xe5\t\n" +
	"\vTaskFeature\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vmodel_class\x18\x02 \x01(\tR\n" +
	"modelClass\x124\n" +
	"\x16estimated_input_tokens\x18\x03 \x01(\x03R\x14estimatedInputTokens\x126\n" +
	"\x17estimated_output_tokens\x18\x04 \x01(\x03R\x15estimatedOutputTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12#\n" +
	"\rtimeout_class\x18\a \x01(\tR\ftimeoutClass\x12&\n" +
	"\x0fenqueue_time_ms\x18\b \x01(\x03R\renqueueTimeMs\x12!\n" +
	"\frequest_kind\x18\t \x01(\tR\vrequestKind\x12\x1d\n" +
	"\n" +
	"route_hint\x18\n" +
	" \x01(\tR\trouteHint\x12$\n" +
	"\x0ehas_tool_calls\x18\v \x01(\bR\fhasToolCalls\x12&\n" +
	"\x0ftool_call_depth\x18\f \x01(\x05R\rtoolCallDepth\x12\x1d\n" +
	"\n" +
	"turn_count\x18\r \x01(\x05R\tturnCount\x12\x1e\n" +
	"\n" +
	"multimodal\x18\x0e \x01(\bR\n" +
	"multimodal\x12%\n" +
	"\x0equestion_count\x18\x0f \x01(\x05R\rquestionCount\x12(\n" +
	"\x10code_block_count\x18\x10 \x01(\x05R\x0ecodeBlockCount\x12)\n" +
	"\x10enumeration_hint\x18\x11 \x01(\bR\x0fenumerationHint\x124\n" +
	"\x16instruction_verb_count\x18\x12 \x01(\x05R\x14instructionVerbCount\x12;\n" +
	"\x1amax_sentence_length_bucket\x18\x13 \x01(\x05R\x17maxSentenceLengthBucket\x12<\n" +
	"\x1avocabulary_richness_bucket\x18\x14 \x01(\x05R\x18vocabularyRichnessBucket\x12'\n" +
	"\x0fconfidence_hint\x18\x15 \x01(\x01R\x0econfidenceHint\x12)\n" +
	"\x10uncertainty_hint\x18\x16 \x01(\x01R\x0funcertaintyHint\x12%\n" +
	"\x0eneighbor_count\x18\x17 \x01(\x03R\rneighborCount\x12$\n" +
	"\x0elatency_p50_ms\x18\x18 \x01(\x03R\flatencyP50Ms\x12$\n" +
	"\x0elatency_p90_ms\x18\x19 \x01(\x03R\flatencyP90Ms\x12*\n" +
	"\x11latency_stddev_ms\x18\x1a \x01(\x01R\x0flatencyStddevMs\x12*\n" +
	"\x11output_tokens_p70\x18\x1b \x01(\x03R\x0foutputTokensP70\x12!\n" +
	"\fsuccess_rate\x18\x1c \x01(\x01R\vsuccessRate\x12!\n" +
	"\ftimeout_rate\x18\x1d \x01(\x01R\vtimeoutRate\x12%\n" +
	"\x0ecoverage_level\x18\x1e \x01(\tR\rcoverageLevel\x12%\n" +
	"\x0ecoverage_ratio\x18\x1f \x01(\x01R\rcoverageRatio\"R\n" +
	"\x14BatchPredictResponse\x12:\n" +
	"\vpredictions\x18\x01 \x03(\v2\x18.predictor.v1.PredictionR\vpredictions\"\xc9\x02\n" +
	"\n" +
	"Prediction\x12E\n" +
	"\tquantiles\x18\x01 \x03(\v2'.predictor.v1.Prediction.QuantilesEntryR\tquantiles\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12?\n" +
	"\asignals\x18\x03 \x03(\v2%.predictor.v1.Prediction.SignalsEntryR\asignals\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a<\n" +
	"\x0eQuantilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a:\n" +
	"\fSignalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xb2\x01\n" +
	"\x14OutputTokenPredictor\x12C\n" +
	"\x06Health\x12\x1b.predictor.v1.HealthRequest\x1a\x1c.predictor.v1.HealthResponse\x12U\n" +
	"\fBatchPredict\x12!.predictor.v1.BatchPredictRequest\x1a\".predictor.v1.BatchPredictResponseB6Z4veloxmesh/internal/scheduler/predictorv1;predictorv1b\x06proto3"

var (
	file_predictor_proto_rawDescOnce sync.Once
	file_predictor_proto_rawDescData []byte
)

func file_predictor_proto_rawDescGZIP() []byte {
	file_predictor_proto_rawDescOnce.Do(func() {
		file_predictor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predictor_proto_rawDesc), len(file_predictor_proto_rawDesc)))
	})
	return file_predictor_proto_rawDescData
}

var file_predictor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_predictor_proto_goTypes = []any{
	(*HealthRequest)(nil),        // 0: predictor.v1.HealthRequest
	(*HealthResponse)(nil),       // 1: predictor.v1.HealthResponse
	(*BatchPredictRequest)(nil),  // 2: predictor.v1.BatchPredictRequest
	(*TaskFeature)(nil),          // 3: predictor.v1.TaskFeature
	(*BatchPredictResponse)(nil), // 4: predictor.v1.BatchPredictResponse
	(*Prediction)(nil),           // 5: predictor.v1.Prediction
	nil,                          // 6: predictor.v1.Prediction.QuantilesEntry
	nil,                          // 7: predictor.v1.Prediction.SignalsEntry
}
var file_predictor_proto_depIdxs = []int32{
	3, // 0: predictor.v1.BatchPredictRequest.tasks:type_name -> predictor.v1.TaskFeature
	5, // 1: predictor.v1.BatchPredictResponse.predictions:type_name -> predictor.v1.Prediction
	6, // 2: predictor.v1.Prediction.quantiles:type_name -> predictor.v1.Prediction.QuantilesEntry
	7, // 3: predictor.v1.Prediction.signals:type_name -> predictor.v1.Prediction.SignalsEntry
	0, // 4: predictor.v1.OutputTokenPredictor.Health:input_type -> predictor.v1.HealthRequest
	2, // 5: predictor.v1.OutputTokenPredictor.BatchPredict:input_type -> predictor.v1.BatchPredictRequest
	1, // 6: predictor.v1.OutputTokenPredictor.Health:output_type -> predictor.v1.HealthResponse
	4, // 7: predictor.v1.OutputTokenPredictor.BatchPredict:output_type -> predictor.v1.BatchPredictResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_predictor_proto_init() }
func file_predictor_proto_init() {
	if File_predictor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predictor_proto_rawDesc), len(file_predictor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predictor_proto_goTypes,
		DependencyIndexes: file_predictor_proto_depIdxs,
		MessageInfos:      file_predictor_proto_msgTypes,
	}.Build()
	File_predictor_proto = out.File
	file_predictor_proto_goTypes = nil
	file_predictor_proto_depIdxs = nil
}
