// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/scheduler/v1/scheduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskFeature         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScoreRequest) Reset() {
	*x = BatchScoreRequest{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScoreRequest) ProtoMessage() {}

func (x *BatchScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScoreRequest.ProtoReflect.Descriptor instead.
func (*BatchScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *BatchScoreRequest) GetTasks() []*TaskFeature {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskFeature struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TaskId                   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ModelClass               string                 `protobuf:"bytes,2,opt,name=model_class,json=modelClass,proto3" json:"model_class,omitempty"`
	EstimatedInputTokens     int64                  `protobuf:"varint,3,opt,name=estimated_input_tokens,json=estimatedInputTokens,proto3" json:"estimated_input_tokens,omitempty"`
	EstimatedOutputTokens    int64                  `protobuf:"varint,4,opt,name=estimated_output_tokens,json=estimatedOutputTokens,proto3" json:"estimated_output_tokens,omitempty"`
	Stream                   bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	Priority                 string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutClass             string                 `protobuf:"bytes,7,opt,name=timeout_class,json=timeoutClass,proto3" json:"timeout_class,omitempty"`
	EnqueueTimeMs            int64                  `protobuf:"varint,8,opt,name=enqueue_time_ms,json=enqueueTimeMs,proto3" json:"enqueue_time_ms,omitempty"`
	RequestKind              string                 `protobuf:"bytes,9,opt,name=request_kind,json=requestKind,proto3" json:"request_kind,omitempty"`
	RouteHint                string                 `protobuf:"bytes,10,opt,name=route_hint,json=routeHint,proto3" json:"route_hint,omitempty"`
	HasToolCalls             bool                   `protobuf:"varint,11,opt,name=has_tool_calls,json=hasToolCalls,proto3" json:"has_tool_calls,omitempty"`
	ToolCallDepth            int32                  `protobuf:"varint,12,opt,name=tool_call_depth,json=toolCallDepth,proto3" json:"tool_call_depth,omitempty"`
	TurnCount                int32                  `protobuf:"varint,13,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	Multimodal               bool                   `protobuf:"varint,14,opt,name=multimodal,proto3" json:"multimodal,omitempty"`
	QuestionCount            int32                  `protobuf:"varint,15,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	CodeBlockCount           int32                  `protobuf:"varint,16,opt,name=code_block_count,json=codeBlockCount,proto3" json:"code_block_count,omitempty"`
	EnumerationHint          bool                   `protobuf:"varint,17,opt,name=enumeration_hint,json=enumerationHint,proto3" json:"enumeration_hint,omitempty"`
	InstructionVerbCount     int32                  `protobuf:"varint,18,opt,name=instruction_verb_count,json=instructionVerbCount,proto3" json:"instruction_verb_count,omitempty"`
	MaxSentenceLengthBucket  int32                  `protobuf:"varint,19,opt,name=max_sentence_length_bucket,json=maxSentenceLengthBucket,proto3" json:"max_sentence_length_bucket,omitempty"`
	VocabularyRichnessBucket int32                  `protobuf:"varint,20,opt,name=vocabulary_richness_bucket,json=vocabularyRichnessBucket,proto3" json:"vocabulary_richness_bucket,omitempty"`
	ConfidenceHint           float64                `protobuf:"fixed64,21,opt,name=confidence_hint,json=confidenceHint,proto3" json:"confidence_hint,omitempty"`
	UncertaintyHint          float64                `protobuf:"fixed64,22,opt,name=uncertainty_hint,json=uncertaintyHint,proto3" json:"uncertainty_hint,omitempty"`
	NeighborCount            int64                  `protobuf:"varint,23,opt,name=neighbor_count,json=neighborCount,proto3" json:"neighbor_count,omitempty"`
	LatencyP50Ms             int64                  `protobuf:"varint,24,opt,name=latency_p50_ms,json=latencyP50Ms,proto3" json:"latency_p50_ms,omitempty"`
	LatencyP90Ms             int64                  `protobuf:"varint,25,opt,name=latency_p90_ms,json=latencyP90Ms,proto3" json:"latency_p90_ms,omitempty"`
	LatencyStddevMs          float64                `protobuf:"fixed64,26,opt,name=latency_stddev_ms,json=latencyStddevMs,proto3" json:"latency_stddev_ms,omitempty"`
	OutputTokensP70          int64                  `protobuf:"varint,27,opt,name=output_tokens_p70,json=outputTokensP70,proto3" json:"output_tokens_p70,omitempty"`
	SuccessRate              float64                `protobuf:"fixed64,28,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	TimeoutRate              float64                `protobuf:"fixed64,29,opt,name=timeout_rate,json=timeoutRate,proto3" json:"timeout_rate,omitempty"`
	CoverageLevel            string                 `protobuf:"bytes,30,opt,name=coverage_level,json=coverageLevel,proto3" json:"coverage_level,omitempty"`
	CoverageRatio            float64                `protobuf:"fixed64,31,opt,name=coverage_ratio,json=coverageRatio,proto3" json:"coverage_ratio,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TaskFeature) Reset() {
	*x = TaskFeature{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFeature) ProtoMessage() {}

func (x *TaskFeature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFeature.ProtoReflect.Descriptor instead.
func (*TaskFeature) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *TaskFeature) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFeature) GetModelClass() string {
	if x != nil {
		return x.ModelClass
	}
	return ""
}

func (x *TaskFeature) GetEstimatedInputTokens() int64 {
	if x != nil {
		return x.EstimatedInputTokens
	}
	return 0
}

func (x *TaskFeature) GetEstimatedOutputTokens() int64 {
	if x != nil {
		return x.EstimatedOutputTokens
	}
	return 0
}

func (x *TaskFeature) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *TaskFeature) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *TaskFeature) GetTimeoutClass() string {
	if x != nil {
		return x.TimeoutClass
	}
	return ""
}

func (x *TaskFeature) GetEnqueueTimeMs() int64 {
	if x != nil {
		return x.EnqueueTimeMs
	}
	return 0
}

func (x *TaskFeature) GetRequestKind() string {
	if x != nil {
		return x.RequestKind
	}
	return ""
}

func (x *TaskFeature) GetRouteHint() string {
	if x != nil {
		return x.RouteHint
	}
	return ""
}

func (x *TaskFeature) GetHasToolCalls() bool {
	if x != nil {
		return x.HasToolCalls
	}
	return false
}

func (x *TaskFeature) GetToolCallDepth() int32 {
	if x != nil {
		return x.ToolCallDepth
	}
	return 0
}

func (x *TaskFeature) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *TaskFeature) GetMultimodal() bool {
	if x != nil {
		return x.Multimodal
	}
	return false
}

func (x *TaskFeature) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *TaskFeature) GetCodeBlockCount() int32 {
	if x != nil {
		return x.CodeBlockCount
	}
	return 0
}

func (x *TaskFeature) GetEnumerationHint() bool {
	if x != nil {
		return x.EnumerationHint
	}
	return false
}

func (x *TaskFeature) GetInstructionVerbCount() int32 {
	if x != nil {
		return x.InstructionVerbCount
	}
	return 0
}

func (x *TaskFeature) GetMaxSentenceLengthBucket() int32 {
	if x != nil {
		return x.MaxSentenceLengthBucket
	}
	return 0
}

func (x *TaskFeature) GetVocabularyRichnessBucket() int32 {
	if x != nil {
		return x.VocabularyRichnessBucket
	}
	return 0
}

func (x *TaskFeature) GetConfidenceHint() float64 {
	if x != nil {
		return x.ConfidenceHint
	}
	return 0
}

func (x *TaskFeature) GetUncertaintyHint() float64 {
	if x != nil {
		return x.UncertaintyHint
	}
	return 0
}

func (x *TaskFeature) GetNeighborCount() int64 {
	if x != nil {
		return x.NeighborCount
	}
	return 0
}

func (x *TaskFeature) GetLatencyP50Ms() int64 {
	if x != nil {
		return x.LatencyP50Ms
	}
	return 0
}

func (x *TaskFeature) GetLatencyP90Ms() int64 {
	if x != nil {
		return x.LatencyP90Ms
	}
	return 0
}

func (x *TaskFeature) GetLatencyStddevMs() float64 {
	if x != nil {
		return x.LatencyStddevMs
	}
	return 0
}

func (x *TaskFeature) GetOutputTokensP70() int64 {
	if x != nil {
		return x.OutputTokensP70
	}
	return 0
}

func (x *TaskFeature) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *TaskFeature) GetTimeoutRate() float64 {
	if x != nil {
		return x.TimeoutRate
	}
	return 0
}

func (x *TaskFeature) GetCoverageLevel() string {
	if x != nil {
		return x.CoverageLevel
	}
	return ""
}

func (x *TaskFeature) GetCoverageRatio() float64 {
	if x != nil {
		return x.CoverageRatio
	}
	return 0
}

type BatchScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoreResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScoreResponse) Reset() {
	*x = BatchScoreResponse{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScoreResponse) ProtoMessage() {}

func (x *BatchScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScoreResponse.ProtoReflect.Descriptor instead.
func (*BatchScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *BatchScoreResponse) GetResults() []*ScoreResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ScoreResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Score              float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Priority           string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	PredictedLatencyMs int64                  `protobuf:"varint,4,opt,name=predicted_latency_ms,json=predictedLatencyMs,proto3" json:"predicted_latency_ms,omitempty"`
	Confidence         float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SchedulerVersion   string                 `protobuf:"bytes,6,opt,name=scheduler_version,json=schedulerVersion,proto3" json:"scheduler_version,omitempty"`
	Reason             string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScoreResult) Reset() {
	*x = ScoreResult{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResult) ProtoMessage() {}

func (x *ScoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResult.ProtoReflect.Descriptor instead.
func (*ScoreResult) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScoreResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreResult) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ScoreResult) GetPredictedLatencyMs() int64 {
	if x != nil {
		return x.PredictedLatencyMs
	}
	return 0
}

func (x *ScoreResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ScoreResult) GetSchedulerVersion() string {
	if x != nil {
		return x.SchedulerVersion
	}
	return ""
}

func (x *ScoreResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\"proto/scheduler/v1/scheduler.proto\x12\fscheduler.v1\"D\n" +
	"\x11BatchScoreRequest\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.scheduler.v1.TaskFeatureR\x05tasks\"\x86\a\n" +
	"\vTaskFeature\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vmodel_class\x18\x02 \x01(\tR\n" +
	"modelClass\x124\n" +
	"\x16estimated_input_tokens\x18\x03 \x01(\x03R\x14estimatedInputTokens\x126\n" +
	"\x17estimated_output_tokens\x18\x04 \x01(\x03R\x15estimatedOutputTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12#\n" +
	"\rtimeout_class\x18\a \x01(\tR\ftimeoutClass\x12&\n" +
	"\x0fenqueue_time_ms\x18\b \x01(\x03R\renqueueTimeMs\x12!\n" +
	"\frequest_kind\x18\t \x01(\tR\vrequestKind\x12\x1d\n" +
	"\n" +
	"route_hint\x18\n" +
	" \x01(\tR\trouteHint\x12$\n" +
	"\x0ehas_tool_calls\x18\v \x01(\bR\fhasToolCalls\x12&\n" +
	"\x0ftool_call_depth\x18\f \x01(\x05R\rtoolCallDepth\x12\x1d\n" +
	"\n" +
	"turn_count\x18\r \x01(\x05R\tturnCount\x12\x1e\n" +
	"\n" +
	"multimodal\x18\x0e \x01(\bR\n" +
	"multimodal\x12%\n" +
	"\x0equestion_count\x18\x0f \x01(\x05R\rquestionCount\x12(\n" +
	"\x10code_block_count\x18\x10 \x01(\x05R\x0ecodeBlockCount\x12)\n" +
	"\x10enumeration_hint\x18\x11 \x01(\bR\x0fenumerationHint\x124\n" +
	"\x16instruction_verb_count\x18\x12 \x01(\x05R\x14instructionVerbCount\x12;\n" +
	"\x1amax_sentence_length_bucket\x18\x13 \x01(\x05R\x17maxSentenceLengthBucket\x12<\n" +
	"\x1avocabulary_richness_bucket\x18\x14 \x01(\x05R\x18vocabularyRichnessBucket\x12'\n" +
	"\x0fconfidence_hint\x18\x15 \x01(\x01R\x0econfidenceHint\x12)\n" +
	"\x10uncertainty_hint\x18\x16 \x01(\x01R\x0funcertaintyHint\"I\n" +
	"\x12BatchScoreResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.scheduler.v1.ScoreResultR\aresults\"\xef\x01\n" +
	"\vScoreResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x120\n" +
	"\x14predicted_latency_ms\x18\x04 \x01(\x03R\x12predictedLatencyMs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11scheduler_version\x18\x06 \x01(\tR\x10schedulerVersion\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason2e\n" +
	"\rTaskScheduler\x12T\n" +
	"\x0fBatchScoreTasks\x12\x1f.scheduler.v1.BatchScoreRequest\x1a .scheduler.v1.BatchScoreResponseB6Z4veloxmesh/internal/scheduler/schedulerv1;schedulerv1b\x06proto3"

var (
	file_proto_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_v1_scheduler_proto_rawDesc), len(file_proto_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_v1_scheduler_proto_rawDescData
}

var file_proto_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scheduler_v1_scheduler_proto_goTypes = []any{
	(*BatchScoreRequest)(nil),  // 0: scheduler.v1.BatchScoreRequest
	(*TaskFeature)(nil),        // 1: scheduler.v1.TaskFeature
	(*BatchScoreResponse)(nil), // 2: scheduler.v1.BatchScoreResponse
	(*ScoreResult)(nil),        // 3: scheduler.v1.ScoreResult
}
var file_proto_scheduler_v1_scheduler_proto_depIdxs = []int32{
	1, // 0: scheduler.v1.BatchScoreRequest.tasks:type_name -> scheduler.v1.TaskFeature
	3, // 1: scheduler.v1.BatchScoreResponse.results:type_name -> scheduler.v1.ScoreResult
	0, // 2: scheduler.v1.TaskScheduler.BatchScoreTasks:input_type -> scheduler.v1.BatchScoreRequest
	2, // 3: scheduler.v1.TaskScheduler.BatchScoreTasks:output_type -> scheduler.v1.BatchScoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scheduler_v1_scheduler_proto_init() }
func file_proto_scheduler_v1_scheduler_proto_init() {
	if File_proto_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_v1_scheduler_proto_rawDesc), len(file_proto_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_v1_scheduler_proto = out.File
	file_proto_scheduler_v1_scheduler_proto_goTypes = nil
	file_proto_scheduler_v1_scheduler_proto_depIdxs = nil
}
